# Generated by Django 4.2.5 on 2023-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=80, unique=True)),
                ('product_description', models.TextField(max_length=350)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
